framework:
    cache:
        # Cache principal — filesystem (rapide et sans installation)
        app: cache.adapter.filesystem

        # Pool dédié pour les réponses Doctrine
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.query_cache_pool:
                adapter: cache.adapter.filesystem