<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EfOFfDCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EfOFfDC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EfOFfDC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repas' => ['privates', '.errored..service_locator.EfOFfDC.App\\Entity\\Repas', NULL, 'Cannot autowire service ".service_locator.EfOFfDC": it needs an instance of "App\\Entity\\Repas" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repas' => 'App\\Entity\\Repas',
            'entityManager' => '?',
        ]);
    }
}
