<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UaROwQMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UaROwQM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UaROwQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'question' => ['privates', '.errored..service_locator.UaROwQM.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.UaROwQM": it needs an instance of "App\\Entity\\Question" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'question' => 'App\\Entity\\Question',
            'em' => '?',
        ]);
    }
}
