<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NYnQ_PKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NYnQ.PK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NYnQ.PK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repasRepository' => ['privates', 'App\\Repository\\RepasRepository', 'getRepasRepositoryService', true],
        ], [
            'repasRepository' => 'App\\Repository\\RepasRepository',
        ]);
    }
}
