<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CertificationController' shared autowired service.
     *
     * @return \App\Controller\CertificationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CertificationController'] = $instance = new \App\Controller\CertificationController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\CertificationController', $container));

        return $instance;
    }
}
