<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunityControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ozDSQUx.App\Controller\CommunityController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ozDSQUx.App\\Controller\\CommunityController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeSoutienRepository' => ['privates', 'App\\Repository\\GroupeSoutienRepository', 'getGroupeSoutienRepositoryService', true],
            'evenementSanteRepository' => ['privates', 'App\\Repository\\EvenementSanteRepository', 'getEvenementSanteRepositoryService', true],
            'membreGroupeRepository' => ['privates', 'App\\Repository\\MembreGroupeRepository', 'getMembreGroupeRepositoryService', true],
        ], [
            'groupeSoutienRepository' => 'App\\Repository\\GroupeSoutienRepository',
            'evenementSanteRepository' => 'App\\Repository\\EvenementSanteRepository',
            'membreGroupeRepository' => 'App\\Repository\\MembreGroupeRepository',
        ]))->withContext('App\\Controller\\CommunityController::index()', $container);
    }
}
