<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L97OtLY.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L97OtLY.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repasRepository' => ['privates', 'App\\Repository\\RepasRepository', 'getRepasRepositoryService', true],
            'seanceSportRepository' => ['privates', 'App\\Repository\\SeanceSportRepository', 'getSeanceSportRepositoryService', true],
            'rendezVousRepository' => ['privates', 'App\\Repository\\RendezVousRepository', 'getRendezVousRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'repasRepository' => 'App\\Repository\\RepasRepository',
            'seanceSportRepository' => 'App\\Repository\\SeanceSportRepository',
            'rendezVousRepository' => 'App\\Repository\\RendezVousRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
