<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalAdminControllereditQuizService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ypOtnZl.App\Controller\MentalAdminController::editQuiz()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ypOtnZl'] ?? $container->load('get_ServiceLocator_YpOtnZlService'));

        if (isset($container->privates['.service_locator.ypOtnZl.App\\Controller\\MentalAdminController::editQuiz()'])) {
            return $container->privates['.service_locator.ypOtnZl.App\\Controller\\MentalAdminController::editQuiz()'];
        }

        return $container->privates['.service_locator.ypOtnZl.App\\Controller\\MentalAdminController::editQuiz()'] = $a->withContext('App\\Controller\\MentalAdminController::editQuiz()', $container);
    }
}
