<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalAdminControllereditQuestionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UaROwQM.App\Controller\MentalAdminController::editQuestion()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.UaROwQM'] ?? $container->load('get_ServiceLocator_UaROwQMService'));

        if (isset($container->privates['.service_locator.UaROwQM.App\\Controller\\MentalAdminController::editQuestion()'])) {
            return $container->privates['.service_locator.UaROwQM.App\\Controller\\MentalAdminController::editQuestion()'];
        }

        return $container->privates['.service_locator.UaROwQM.App\\Controller\\MentalAdminController::editQuestion()'] = $a->withContext('App\\Controller\\MentalAdminController::editQuestion()', $container);
    }
}
