<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalAdminControllerlistQuestionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KB9ApBT.App\Controller\MentalAdminController::listQuestions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KB9ApBT.App\\Controller\\MentalAdminController::listQuestions()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
        ], [
            'questionRepository' => 'App\\Repository\\QuestionRepository',
        ]))->withContext('App\\Controller\\MentalAdminController::listQuestions()', $container);
    }
}
