<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ct_qx9I.App\Controller\MentalController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ct_qx9I.App\\Controller\\MentalController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quiz' => ['privates', '.errored..service_locator.Ct_qx9I.App\\Entity\\QuizMental', NULL, 'Cannot autowire service ".service_locator.Ct_qx9I": it needs an instance of "App\\Entity\\QuizMental" but this type has been excluded in "config/services.yaml".'],
        ], [
            'quiz' => 'App\\Entity\\QuizMental',
        ]))->withContext('App\\Controller\\MentalController::show()', $container);
    }
}
