<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicalControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nGltKPI.App\Controller\MedicalController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nGltKPI.App\\Controller\\MedicalController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rdv' => ['privates', '.errored..service_locator.nGltKPI.App\\Entity\\RendezVous', NULL, 'Cannot autowire service ".service_locator.nGltKPI": it needs an instance of "App\\Entity\\RendezVous" but this type has been excluded in "config/services.yaml".'],
        ], [
            'rdv' => 'App\\Entity\\RendezVous',
        ]))->withContext('App\\Controller\\MedicalController::show()', $container);
    }
}
