<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionAdminControllerusersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tdgAvm5.App\Controller\Admin\NutritionAdminController::users()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tdgAvm5.App\\Controller\\Admin\\NutritionAdminController::users()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\Admin\\NutritionAdminController::users()', $container);
    }
}
