<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NutritionController' shared autowired service.
     *
     * @return \App\Controller\NutritionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\NutritionController'] = $instance = new \App\Controller\NutritionController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\NutritionController', $container));

        return $instance;
    }
}
