<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizMentalTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\QuizMentalType' shared autowired service.
     *
     * @return \App\Form\QuizMentalType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\QuizMentalType'] = new \App\Form\QuizMentalType();
    }
}
