<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RepasRepository' shared autowired service.
     *
     * @return \App\Repository\RepasRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RepasRepository'] = new \App\Repository\RepasRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
