<?php

namespace ContainerWf0tu3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WOvDCXR.App\Controller\RepasController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WOvDCXR'] ?? $container->load('get_ServiceLocator_WOvDCXRService'));

        if (isset($container->privates['.service_locator.WOvDCXR.App\\Controller\\RepasController::delete()'])) {
            return $container->privates['.service_locator.WOvDCXR.App\\Controller\\RepasController::delete()'];
        }

        return $container->privates['.service_locator.WOvDCXR.App\\Controller\\RepasController::delete()'] = $a->withContext('App\\Controller\\RepasController::delete()', $container);
    }
}
