<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XphA4epService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xphA4ep' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xphA4ep'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'seance' => ['privates', '.errored..service_locator.xphA4ep.App\\Entity\\SeanceSport', NULL, 'Cannot autowire service ".service_locator.xphA4ep": it needs an instance of "App\\Entity\\SeanceSport" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'seance' => 'App\\Entity\\SeanceSport',
            'entityManager' => '?',
        ]);
    }
}
