<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AlimentType' shared autowired service.
     *
     * @return \App\Form\AlimentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AlimentType'] = new \App\Form\AlimentType();
    }
}
