<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAliment1TypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Aliment1Type' shared autowired service.
     *
     * @return \App\Form\Aliment1Type
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Aliment1Type'] = new \App\Form\Aliment1Type();
    }
}
