<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fPjRyNz.App\Controller\AlimentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fPjRyNz.App\\Controller\\AlimentController::index()'] = ($container->privates['.service_locator.fPjRyNz'] ?? $container->load('get_ServiceLocator_FPjRyNzService'))->withContext('App\\Controller\\AlimentController::index()', $container);
    }
}
