<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AlimentRepository' shared autowired service.
     *
     * @return \App\Repository\AlimentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AlimentRepository'] = new \App\Repository\AlimentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
