<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunityControllerleaveGroupeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XxW6lM4.App\Controller\CommunityController::leaveGroupe()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.XxW6lM4'] ?? $container->load('get_ServiceLocator_XxW6lM4Service'));

        if (isset($container->privates['.service_locator.XxW6lM4.App\\Controller\\CommunityController::leaveGroupe()'])) {
            return $container->privates['.service_locator.XxW6lM4.App\\Controller\\CommunityController::leaveGroupe()'];
        }

        return $container->privates['.service_locator.XxW6lM4.App\\Controller\\CommunityController::leaveGroupe()'] = $a->withContext('App\\Controller\\CommunityController::leaveGroupe()', $container);
    }
}
