<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunityControllershowGroupeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.71yIUZV.App\Controller\CommunityController::showGroupe()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.71yIUZV.App\\Controller\\CommunityController::showGroupe()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeSoutienRepository' => ['privates', 'App\\Repository\\GroupeSoutienRepository', 'getGroupeSoutienRepositoryService', true],
            'membreGroupeRepository' => ['privates', 'App\\Repository\\MembreGroupeRepository', 'getMembreGroupeRepositoryService', true],
        ], [
            'groupeSoutienRepository' => 'App\\Repository\\GroupeSoutienRepository',
            'membreGroupeRepository' => 'App\\Repository\\MembreGroupeRepository',
        ]))->withContext('App\\Controller\\CommunityController::showGroupe()', $container);
    }
}
