<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicalControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.azCU.DJ.App\Controller\MedicalController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.azCU.DJ'] ?? $container->load('get_ServiceLocator_AzCU_DJService'));

        if (isset($container->privates['.service_locator.azCU.DJ.App\\Controller\\MedicalController::edit()'])) {
            return $container->privates['.service_locator.azCU.DJ.App\\Controller\\MedicalController::edit()'];
        }

        return $container->privates['.service_locator.azCU.DJ.App\\Controller\\MedicalController::edit()'] = $a->withContext('App\\Controller\\MedicalController::edit()', $container);
    }
}
