<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r.9mbzj.App\Controller\MentalController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r.9mbzj.App\\Controller\\MentalController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quizMentalRepository' => ['privates', 'App\\Repository\\QuizMentalRepository', 'getQuizMentalRepositoryService', true],
        ], [
            'quizMentalRepository' => 'App\\Repository\\QuizMentalRepository',
        ]))->withContext('App\\Controller\\MentalController::index()', $container);
    }
}
