<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalAdminControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WQpO4L_.App\Controller\MentalAdminController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WQpO4L_.App\\Controller\\MentalAdminController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\MentalAdminController::dashboard()', $container);
    }
}
