<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MentalController' shared autowired service.
     *
     * @return \App\Controller\MentalController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MentalController'] = $instance = new \App\Controller\MentalController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\MentalController', $container));

        return $instance;
    }
}
