<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentalControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BFHZspJ.App\Controller\MentalController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BFHZspJ.App\\Controller\\MentalController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quiz' => ['privates', '.errored..service_locator.BFHZspJ.App\\Entity\\QuizMental', NULL, 'Cannot autowire service ".service_locator.BFHZspJ": it needs an instance of "App\\Entity\\QuizMental" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'quiz' => 'App\\Entity\\QuizMental',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\MentalController::delete()', $container);
    }
}
