<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicalControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.osshsJl.App\Controller\MedicalController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.osshsJl.App\\Controller\\MedicalController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rendezVousRepository' => ['privates', 'App\\Repository\\RendezVousRepository', 'getRendezVousRepositoryService', true],
            'specialisteRepository' => ['privates', 'App\\Repository\\SpecialisteRepository', 'getSpecialisteRepositoryService', true],
        ], [
            'rendezVousRepository' => 'App\\Repository\\RendezVousRepository',
            'specialisteRepository' => 'App\\Repository\\SpecialisteRepository',
        ]))->withContext('App\\Controller\\MedicalController::index()', $container);
    }
}
