<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionAdminControllermealFoodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.91lnPwz.App\Controller\Admin\NutritionAdminController::mealFoods()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.91lnPwz.App\\Controller\\Admin\\NutritionAdminController::mealFoods()'] = ($container->privates['.service_locator.91lnPwz'] ?? $container->load('get_ServiceLocator_91lnPwzService'))->withContext('App\\Controller\\Admin\\NutritionAdminController::mealFoods()', $container);
    }
}
