<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionAdminControlleruserMealsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kmSk9AQ.App\Controller\Admin\NutritionAdminController::userMeals()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kmSk9AQ.App\\Controller\\Admin\\NutritionAdminController::userMeals()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.kmSk9AQ.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.kmSk9AQ": it needs an instance of "App\\Entity\\Utilisateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'user' => 'App\\Entity\\Utilisateur',
        ]))->withContext('App\\Controller\\Admin\\NutritionAdminController::userMeals()', $container);
    }
}
