<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EfOFfDC.App\Controller\NutritionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.EfOFfDC'] ?? $container->load('get_ServiceLocator_EfOFfDCService'));

        if (isset($container->privates['.service_locator.EfOFfDC.App\\Controller\\NutritionController::delete()'])) {
            return $container->privates['.service_locator.EfOFfDC.App\\Controller\\NutritionController::delete()'];
        }

        return $container->privates['.service_locator.EfOFfDC.App\\Controller\\NutritionController::delete()'] = $a->withContext('App\\Controller\\NutritionController::delete()', $container);
    }
}
