<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NYnQ.PK.App\Controller\RepasController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NYnQ.PK.App\\Controller\\RepasController::index()'] = ($container->privates['.service_locator.NYnQ.PK'] ?? $container->load('get_ServiceLocator_NYnQ_PKService'))->withContext('App\\Controller\\RepasController::index()', $container);
    }
}
