<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRendezVousService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.azCU.DJ.App\Entity\RendezVous' shared service.
     *
     * @return \App\Entity\RendezVous
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.azCU.DJ": it needs an instance of "App\\Entity\\RendezVous" but this type has been excluded in "config/services.yaml".');
    }
}
