<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportsControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BwImlFv.App\Controller\SportsController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BwImlFv.App\\Controller\\SportsController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'seance' => ['privates', '.errored..service_locator.BwImlFv.App\\Entity\\SeanceSport', NULL, 'Cannot autowire service ".service_locator.BwImlFv": it needs an instance of "App\\Entity\\SeanceSport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'seance' => 'App\\Entity\\SeanceSport',
        ]))->withContext('App\\Controller\\SportsController::show()', $container);
    }
}
