<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportsControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xphA4ep.App\Controller\SportsController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xphA4ep'] ?? $container->load('get_ServiceLocator_XphA4epService'));

        if (isset($container->privates['.service_locator.xphA4ep.App\\Controller\\SportsController::delete()'])) {
            return $container->privates['.service_locator.xphA4ep.App\\Controller\\SportsController::delete()'];
        }

        return $container->privates['.service_locator.xphA4ep.App\\Controller\\SportsController::delete()'] = $a->withContext('App\\Controller\\SportsController::delete()', $container);
    }
}
