<?php

namespace ContainerJxO4yDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeanceSportRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SeanceSportRepository' shared autowired service.
     *
     * @return \App\Repository\SeanceSportRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SeanceSportRepository'] = new \App\Repository\SeanceSportRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
