<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateInscription' => [parent::class, 'dateInscription', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'membresGroupes' => [parent::class, 'membresGroupes', null, 16],
        "\0".parent::class."\0".'motDePasse' => [parent::class, 'motDePasse', null, 16],
        "\0".parent::class."\0".'nomComplet' => [parent::class, 'nomComplet', null, 16],
        "\0".parent::class."\0".'profilSante' => [parent::class, 'profilSante', null, 16],
        "\0".parent::class."\0".'quizMentaux' => [parent::class, 'quizMentaux', null, 16],
        "\0".parent::class."\0".'rendezVous' => [parent::class, 'rendezVous', null, 16],
        "\0".parent::class."\0".'repas' => [parent::class, 'repas', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'scoreGlobal' => [parent::class, 'scoreGlobal', null, 16],
        "\0".parent::class."\0".'seancesSport' => [parent::class, 'seancesSport', null, 16],
        'dateInscription' => [parent::class, 'dateInscription', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'membresGroupes' => [parent::class, 'membresGroupes', null, 16],
        'motDePasse' => [parent::class, 'motDePasse', null, 16],
        'nomComplet' => [parent::class, 'nomComplet', null, 16],
        'profilSante' => [parent::class, 'profilSante', null, 16],
        'quizMentaux' => [parent::class, 'quizMentaux', null, 16],
        'rendezVous' => [parent::class, 'rendezVous', null, 16],
        'repas' => [parent::class, 'repas', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'scoreGlobal' => [parent::class, 'scoreGlobal', null, 16],
        'seancesSport' => [parent::class, 'seancesSport', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
