<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Repas extends \App\Entity\Repas implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aliments' => [parent::class, 'aliments', null, 16],
        "\0".parent::class."\0".'dateConsommation' => [parent::class, 'dateConsommation', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'pointsGagnes' => [parent::class, 'pointsGagnes', null, 16],
        "\0".parent::class."\0".'titreRepas' => [parent::class, 'titreRepas', null, 16],
        "\0".parent::class."\0".'typeMoment' => [parent::class, 'typeMoment', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'aliments' => [parent::class, 'aliments', null, 16],
        'dateConsommation' => [parent::class, 'dateConsommation', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'pointsGagnes' => [parent::class, 'pointsGagnes', null, 16],
        'titreRepas' => [parent::class, 'titreRepas', null, 16],
        'typeMoment' => [parent::class, 'typeMoment', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
